# Theme config.

author = "asjdf"
selfintro = "一只在杭电摸鱼的小火鸡" # appears in the site header when set to a non-empty string
avatar = "img/avatar.jpg" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)

ICP = "闽ICP备2022001901号-1"      # 域名备案
beian = "闽公网安备 35030302354429号" # 公安网备
